brain = [
    ["Individuals are sensitive to their social standing and relative position in a group.", "SCARF Model"],
    ["Acknowledging and respecting others' status can positively influence social dynamics.", "SCARF Model"],
    ["The brain craves predictability and certainty for a sense of safety.", "SCARF Model"],
    ["Creating clear expectations and providing information can reduce anxiety and enhance performance.", "SCARF Model"],
    ["A fundamental need for a sense of control and autonomy exists in people.", "SCARF Model"],
    ["Empowering individuals to make choices and decisions can boost motivation and engagement.", "SCARF Model"],
    ["Social connections and a sense of belonging are vital for well-being.", "SCARF Model"],
    ["Building positive relationships at work fosters collaboration and a supportive environment.", "SCARF Model"],
    ["The brain is highly attuned to fairness and perceived injustice.", "SCARF Model"],
    ["Ensuring fairness in decision-making processes is crucial for trust and team morale.", "SCARF Model"],
    ["Cognitive load refers to the mental effort required for a task.", "Cognitive Load and Energy"],
    ["Simplifying complex tasks, breaking them into smaller steps, and managing interruptions can reduce cognitive load.", "Cognitive Load and Energy"],
    ["The brain has limited cognitive resources, and decision-making consumes energy.", "Cognitive Load and Energy"],
    ["Regular breaks, mindfulness practices, and strategic use of energy can enhance overall productivity.", "Cognitive Load and Energy"],
    ["The brain processes information more effectively when presented in the form of a story.", "Communication and Learning"],
    ["Narratives engage the brain, making information more memorable and impactful.", "Communication and Learning"],
    ["The brain has the ability to reorganize itself and form new neural connections throughout life.", "Neuroplasticity and Learning"],
    ["Learning new skills and adapting to challenges can enhance neuroplasticity.", "Neuroplasticity and Learning"],
    ["Mindfulness practices improve attention, focus, and overall cognitive function.", "Attention and Mindfulness"],
    ["Mindful breaks and regular pauses during the day contribute to enhanced productivity.", "Attention and Mindfulness"],
    ["The brain's emotional response system influences decision-making and behavior.", "Emotional Regulation"],
    ["Developing emotional intelligence helps regulate emotions, fostering resilience in challenging situations.", "Emotional Regulation"],
    ["Constructive feedback positively influences motivation and performance.", "Feedback and Performance"],
    ["Framing feedback as a learning opportunity is more effective than criticism.", "Feedback and Performance"],
    ["Setting clear and achievable goals activates the brain's reward system.", "Goal Setting"],
    ["Breaking down larger goals into smaller tasks enhances motivation and progress.", "Goal Setting"],
    ["Positive social interactions trigger the release of oxytocin, promoting trust and collaboration.", "Social Interactions and Team Dynamics"],
    ["A cohesive team and a supportive work environment contribute to individual and collective well-being.",
     "Social Interactions and Team Dynamics"],
    ["Use positive affirmations to shift your mindset and promote self-compassion.", "Dealing with Emotions Techniques"],
    ["Keep a journal to express and reflect on your thoughts and emotions.", "Dealing with Emotions Techniques"],
    ["Build supportive relationships and share your feelings with trusted friends or family.", "Dealing with Emotions Techniques"],
]

bravely = [
    ["Understanding your own attachment style is key to building healthy relationships.", "Attachment Styles"],
    ["Communicate openly and honestly about your desires, needs, and fears.", "Communication in Relationships"],
    ["Explore your own values and beliefs around love and relationships.", "Personal Values in Relationships"],
    ["Practice self-compassion and self-awareness to enhance emotional well-being.", "Self-Compassion"],
    ["Embrace vulnerability as a strength in building intimate connections.", "Vulnerability in Relationships"],
    ["Cultivate a secure base within yourself to navigate relationship challenges.", "Building a Secure Base"],
    ["Develop empathy to understand and connect with your partner's experiences.", "Empathy in Relationships"],
    ["Prioritize self-care to maintain a strong foundation for relational well-being.", "Self-Care in Relationships"],
    ["Recognize and challenge unrealistic expectations in relationships.", "Managing Expectations"],
    ["Establish healthy boundaries to maintain individual identities within a partnership.", "Setting Boundaries"],
    ["Navigate conflicts constructively through active listening and empathy.", "Conflict Resolution"],
    ["Foster a sense of playfulness and joy in your relationship.", "Playfulness in Relationships"],
    ["Practice gratitude to nurture a positive and appreciative mindset.", "Gratitude in Relationships"],
    ["Explore your love languages and those of your partner for effective communication.", "Love Languages"],
    ["Build a culture of appreciation by acknowledging your partner's strengths.", "Appreciation in Relationships"],
    ["Prioritize quality time for deep connection and intimacy.", "Quality Time in Relationships"],
    ["Develop emotional intelligence to navigate complex feelings in relationships.", "Emotional Intelligence"],
    ["Understand the impact of past experiences on your current relationship dynamics.", "Exploring Past Experiences"],
    ["Acknowledge and address power dynamics within the relationship.", "Power Dynamics"],
    ["Create rituals of connection to strengthen the bond between partners.", "Rituals of Connection"],
    ["Cultivate a sense of curiosity to continue learning about your partner.", "Curiosity in Relationships"],
    ["Celebrate individual growth and support each other's personal development.", "Supporting Growth"],
    ["Express appreciation for your partner's efforts and contributions.", "Expressing Appreciation"],
    ["Navigate differences in sexual desire with open and non-judgmental communication.", "Sexual Intimacy"],
    ["Develop a shared vision for the future to align long-term goals.", "Shared Vision for the Future"],
    ["Practice forgiveness to move forward from past hurts and conflicts.", "Forgiveness in Relationships"],
    ["Create a safe emotional space for your partner to share vulnerabilities.", "Creating Emotional Safety"],
    ["Explore and understand the impact of family-of-origin dynamics on your relationship.", "Family-of-Origin Dynamics"],
    ["Prioritize fun and laughter as integral components of a thriving relationship.", "Fun and Laughter in Relationships"],
    ["Build a foundation of trust through transparency and honesty.", "Building Trust in Relationships"],
    ["Cultivate a sense of gratitude for the growth and learning within your relationship.", "Gratitude for Relationship Growth"],
    ["Regularly reassess and renew relationship goals to foster ongoing connection.", "Renewing Relationship Goals"],
]